/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package todolist_official;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Hocisdabest
 */
public class MainForm extends javax.swing.JFrame {

    public int Taskdone = 0;
    public int LimitTask = 5;
    public int TotalTask = 0;
    public int selectedRow;
    
    public static String LayNgay(){
        java.util.Date currentDate = new java.util.Date();
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
        String formattedDate = dateFormat.format(currentDate);
        return formattedDate;
    }
    private String getUserLogged(){
        String line = "";
        try
    {
        FileReader fr = new FileReader("logged.txt");
        BufferedReader bf = new BufferedReader(fr);
        line = bf.readLine();
    }
    catch (FileNotFoundException e)
    {
        e.printStackTrace();
    }
    catch (IOException e)
    {
        e.printStackTrace();
    }
        return line;
        }
    
    public static boolean CheckDeadLine(String a, String b){
        String FirstDay[] = a.split("/");
        String LastDay[] = b.split("/");
        int FirstDate = Integer.parseInt(FirstDay[0]);
        int FirstMonth = Integer.parseInt(FirstDay[1]);
        int FirstYear = Integer.parseInt(FirstDay[2]);
        
        int LastDate = Integer.parseInt(LastDay[0]);
        int LastMonth = Integer.parseInt(LastDay[1]);
        int LastYear = Integer.parseInt(LastDay[2]);
        
        System.out.print(FirstYear + " " + LastYear);
        if(FirstYear > LastYear) 
        {
            return true;    
        }
        else if(FirstYear == LastYear && FirstMonth > LastMonth){
            return true;
        }
        else if(FirstYear == LastYear && FirstMonth == LastMonth && FirstDate > LastDate){
            return true;
        }
        else{
            System.out.print(FirstDate + " " + LastDate);
            return false;
        }  
    }
        
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Inbox_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Inbox_scrPane = new javax.swing.JScrollPane();
        Papa_AddTask_Panel = new javax.swing.JPanel();
        addtask_label = new javax.swing.JLabel();
        AddTask_panel = new javax.swing.JPanel();
        Taskname_tf = new javax.swing.JTextField();
        Description_tf = new javax.swing.JTextField();
        SetDate_label = new javax.swing.JLabel();
        Priority_cbb = new javax.swing.JComboBox<>();
        cancel_btn = new javax.swing.JButton();
        addtask_btn = new javax.swing.JButton();
        Date_tf = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        Panel_inbox = new javax.swing.JPanel();
        Inbox_icon = new javax.swing.JLabel();
        Inbox_label = new javax.swing.JLabel();
        Today_panel = new javax.swing.JPanel();
        Today_icon = new javax.swing.JLabel();
        Today_label = new javax.swing.JLabel();
        Welcome_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Username_label = new javax.swing.JLabel();
        Tasktable_panel = new javax.swing.JPanel();
        Time_label = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        View_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Task_table = new javax.swing.JTable();
        View_cbb = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        Menu_icon = new javax.swing.JLabel();
        Home_icon = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Search_icon = new javax.swing.JLabel();
        Search_TextField = new javax.swing.JTextField();
        User_icon = new javax.swing.JLabel();
        Taskdone_label = new javax.swing.JLabel();
        JButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ThaiHoc Todo");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/source_icon/user.png")).getImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        Inbox_panel.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setText("INBOX");
        Inbox_panel.add(jLabel1);

        Inbox_scrPane.setBorder(null);
        Inbox_panel.add(Inbox_scrPane);

        addtask_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addtask_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/plus1.png"))); // NOI18N
        addtask_label.setText("Add task");
        addtask_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtask_labelMouseClicked(evt);
            }
        });

        Taskname_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Taskname_tf.setText("Task name");
        Taskname_tf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Taskname_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Taskname_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Taskname_tfFocusLost(evt);
            }
        });
        Taskname_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Taskname_tfKeyTyped(evt);
            }
        });

        Description_tf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Description_tf.setText("Description");
        Description_tf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Description_tf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Description_tfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Description_tfFocusLost(evt);
            }
        });

        SetDate_label.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SetDate_label.setText("Date");

        Priority_cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Priority 1", "Priority 2", "Priority 3", "Priority 4" }));
        Priority_cbb.setSelectedIndex(3);
        Priority_cbb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Priority_cbbActionPerformed(evt);
            }
        });

        cancel_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cancel_btn.setText("Cancel");
        cancel_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_btnMouseClicked(evt);
            }
        });

        addtask_btn.setBackground(new java.awt.Color(255, 51, 51));
        addtask_btn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addtask_btn.setForeground(new java.awt.Color(255, 255, 255));
        addtask_btn.setText("Add Task");
        addtask_btn.setEnabled(false);
        addtask_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addtask_btnMouseClicked(evt);
            }
        });

        Date_tf.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout AddTask_panelLayout = new javax.swing.GroupLayout(AddTask_panel);
        AddTask_panel.setLayout(AddTask_panelLayout);
        AddTask_panelLayout.setHorizontalGroup(
            AddTask_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTask_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AddTask_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddTask_panelLayout.createSequentialGroup()
                        .addComponent(SetDate_label, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(AddTask_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddTask_panelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addtask_btn)
                                .addGap(24, 24, 24))
                            .addGroup(AddTask_panelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(Priority_cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(AddTask_panelLayout.createSequentialGroup()
                        .addGroup(AddTask_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Taskname_tf)
                            .addComponent(Description_tf))
                        .addContainerGap())))
        );
        AddTask_panelLayout.setVerticalGroup(
            AddTask_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTask_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Taskname_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddTask_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Date_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(AddTask_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(SetDate_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Priority_cbb, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(AddTask_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addtask_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Papa_AddTask_PanelLayout = new javax.swing.GroupLayout(Papa_AddTask_Panel);
        Papa_AddTask_Panel.setLayout(Papa_AddTask_PanelLayout);
        Papa_AddTask_PanelLayout.setHorizontalGroup(
            Papa_AddTask_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Papa_AddTask_PanelLayout.createSequentialGroup()
                .addComponent(addtask_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(AddTask_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Papa_AddTask_PanelLayout.setVerticalGroup(
            Papa_AddTask_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Papa_AddTask_PanelLayout.createSequentialGroup()
                .addComponent(addtask_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddTask_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(235, 235, 224));
        jPanel3.setName("left_menu_inner"); // NOI18N

        Panel_inbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_inboxMouseClicked(evt);
            }
        });

        Inbox_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/inbox.png"))); // NOI18N

        Inbox_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Inbox_label.setText("Inbox");

        javax.swing.GroupLayout Panel_inboxLayout = new javax.swing.GroupLayout(Panel_inbox);
        Panel_inbox.setLayout(Panel_inboxLayout);
        Panel_inboxLayout.setHorizontalGroup(
            Panel_inboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_inboxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Inbox_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Inbox_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_inboxLayout.setVerticalGroup(
            Panel_inboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_inboxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_inboxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Inbox_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Inbox_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        Today_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Today_panelMouseClicked(evt);
            }
        });

        Today_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/calendar.png"))); // NOI18N

        Today_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Today_label.setText("Today");

        javax.swing.GroupLayout Today_panelLayout = new javax.swing.GroupLayout(Today_panel);
        Today_panel.setLayout(Today_panelLayout);
        Today_panelLayout.setHorizontalGroup(
            Today_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Today_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Today_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Today_label, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        Today_panelLayout.setVerticalGroup(
            Today_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Today_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Today_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Today_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Today_icon))
                .addContainerGap())
        );

        Welcome_panel.setBackground(new java.awt.Color(235, 235, 224));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Welcome,");

        Username_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Username_label.setText(getUserLogged());

        javax.swing.GroupLayout Welcome_panelLayout = new javax.swing.GroupLayout(Welcome_panel);
        Welcome_panel.setLayout(Welcome_panelLayout);
        Welcome_panelLayout.setHorizontalGroup(
            Welcome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Welcome_panelLayout.createSequentialGroup()
                .addGroup(Welcome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Welcome_panelLayout.setVerticalGroup(
            Welcome_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Welcome_panelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Panel_inbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Today_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Welcome_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(Panel_inbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Today_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Welcome_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );

        Time_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Time_label.setText("Today");

        Date.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Date.setText(LayNgay());

        View_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        View_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/sliders.png"))); // NOI18N
        View_label.setText("View");
        View_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_labelMouseClicked(evt);
            }
        });

        Task_table.setAutoCreateRowSorter(true);
        Task_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task name", "Description", "Priority", "Deadline", "Done"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Task_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Task_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Task_table);

        View_cbb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Default", "Name (A-Z)", "Name (Z-A)", "Deadline", "Priority" }));

        javax.swing.GroupLayout Tasktable_panelLayout = new javax.swing.GroupLayout(Tasktable_panel);
        Tasktable_panel.setLayout(Tasktable_panelLayout);
        Tasktable_panelLayout.setHorizontalGroup(
            Tasktable_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tasktable_panelLayout.createSequentialGroup()
                .addComponent(Time_label, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(260, 260, 260)
                .addComponent(View_label, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(View_cbb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        Tasktable_panelLayout.setVerticalGroup(
            Tasktable_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tasktable_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Tasktable_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tasktable_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Date, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Time_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(View_cbb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(View_label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        Menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/menu1.png"))); // NOI18N
        Menu_icon.setName("menu_icon"); // NOI18N
        Menu_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu_iconMenu_Clicked(evt);
            }
        });

        Home_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/home4.png"))); // NOI18N
        Home_icon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_iconMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));

        Search_icon.setBackground(new java.awt.Color(102, 153, 255));
        Search_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/search.png"))); // NOI18N

        Search_TextField.setBackground(new java.awt.Color(153, 204, 255));
        Search_TextField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Search_TextField.setForeground(new java.awt.Color(255, 255, 255));
        Search_TextField.setText("Search");
        Search_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Search_TextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Search_TextFieldFocusLost(evt);
            }
        });
        Search_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Search_TextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Search_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Search_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Search_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Search_TextField)
        );

        User_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/user1.png"))); // NOI18N

        Taskdone_label.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Taskdone_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/source_icon/check.png"))); // NOI18N
        Taskdone_label.setText("0/5");
        Taskdone_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Taskdone_labelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Menu_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Home_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Taskdone_label, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(User_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Home_icon)
                    .addComponent(User_icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Taskdone_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        JButtonDelete.setText("Delete");
        JButtonDelete.setEnabled(false);
        JButtonDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JButtonDeleteMouseClicked(evt);
            }
        });
        JButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Inbox_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Tasktable_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Papa_AddTask_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(JButtonDelete))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Tasktable_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(JButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Papa_AddTask_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Inbox_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addtask_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtask_labelMouseClicked
        AddTask_panel.setVisible(true);
        if(Taskname_tf.getText() == "Task name" && Description_tf.getText() == "Description"){
            addtask_btn.setEnabled(false);
        }
    }//GEN-LAST:event_addtask_labelMouseClicked

    private void Taskname_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Taskname_tfFocusGained
        if(Taskname_tf.getText().equals("Task name")){
            Taskname_tf.setText("");
        }
    }//GEN-LAST:event_Taskname_tfFocusGained

    private void Taskname_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Taskname_tfFocusLost
        if(Taskname_tf.getText().trim().equals("")){
            Taskname_tf.setText("Task name");
        }
    }//GEN-LAST:event_Taskname_tfFocusLost

    private void Taskname_tfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Taskname_tfKeyTyped
        addtask_btn.setEnabled(true);
    }//GEN-LAST:event_Taskname_tfKeyTyped

    private void Description_tfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Description_tfFocusGained
        if(Description_tf.getText().trim().equals("Description")){
            Description_tf.setText("");
        }
    }//GEN-LAST:event_Description_tfFocusGained

    private void Description_tfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Description_tfFocusLost
        if(Description_tf.getText().trim().equals("")){
            Description_tf.setText("Description");
        }
    }//GEN-LAST:event_Description_tfFocusLost

    private void cancel_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_btnMouseClicked
        AddTask_panel.setVisible(false);
    }//GEN-LAST:event_cancel_btnMouseClicked

    private void addtask_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addtask_btnMouseClicked
        java.text.SimpleDateFormat dateFormat = new java.text.SimpleDateFormat("dd/MM/yyyy");
        String formattedDate = dateFormat.format(Date_tf.getDate());
        if(Taskname_tf.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Bạn chưa điền đầy đủ thông tin cần thiết");
        }
        else{
        DefaultTableModel model = (DefaultTableModel)Task_table.getModel();
        model.addRow(new Object[] {Taskname_tf.getText(), Description_tf.getText(),Priority_cbb.getSelectedItem(), formattedDate, false});
        String text = "<html>Bạn đã thêm nhiệm vụ " + "<font color='red'>" + Taskname_tf.getText() +"</font>" + " với deadline vào " + "<font color='red'>" + formattedDate +"</font>" + "</html>";
        JLabel lb = new JLabel(text);
        Font font = lb.getFont();
        Font newFont = font.deriveFont(20f);
        lb.setFont(newFont);
        Inbox_panel.add(lb);
        Inbox_panel.revalidate();
        JButtonDelete.setEnabled(false);

        try{
            FileWriter fw = new java.io.FileWriter(Username_label.getText() + ".txt", true);
            fw.write(Taskname_tf.getText() + "|");
            fw.write(Description_tf.getText() +"|");
            fw.write(Priority_cbb.getSelectedItem() +"|");
            fw.write(formattedDate +"|");
            fw.write("false" +"\n");
            fw.close();
        }

        catch(java.io.IOException e){
            e.printStackTrace();
            }
        Taskname_tf.setText("Task name");
        Description_tf.setText("Description");
        
        }
    }//GEN-LAST:event_addtask_btnMouseClicked

    private void Panel_inboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_inboxMouseClicked
        Inbox_panel.setVisible(true);
        Tasktable_panel.setVisible(false);
        Papa_AddTask_Panel.setVisible(false);
    }//GEN-LAST:event_Panel_inboxMouseClicked

    private void Today_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Today_panelMouseClicked
        Inbox_panel.setVisible(false);
        Tasktable_panel.setVisible(true);
        Papa_AddTask_Panel.setVisible(true);
        AddTask_panel.setVisible(false);
    }//GEN-LAST:event_Today_panelMouseClicked

    private void View_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_labelMouseClicked
        String Sort = View_cbb.getSelectedItem().toString();
        switch(Sort){
            case "Default":
            {
                DefaultTableModel tableModel = (DefaultTableModel) Task_table.getModel();
                tableModel.setRowCount(0); // Remove all rows
                tableModel.fireTableDataChanged(); // Notify table view to update
                break;
            }
            case "Name (A-Z)":
            {
                DefaultTableModel tableModel = (DefaultTableModel) Task_table.getModel();
                for (int i = 0; i < Task_table.getRowCount() - 1; i++)
                {
                    for (int j = i + 1; j < Task_table.getRowCount(); j++) {
                        String gt1 = (String) tableModel.getValueAt(i, 0);
                        String gt2 = (String) tableModel.getValueAt(j, 0);
                        if (gt1.compareTo(gt2)>0)
                        {
                            Vector<Object> rowData1 = new Vector<>(tableModel.getDataVector().get(i));
                            // Get the data of row 2
                            Vector<Object> rowData2 = new Vector<>(tableModel.getDataVector().get(j));
                            // Set the data of row 1 to row 2
                            tableModel.getDataVector().set(i, rowData2);
                            // Set the data of row 2 to row 1
                            tableModel.getDataVector().set(j, rowData1);
                        }
                    }
                }
                tableModel.fireTableDataChanged();
                break;
            }

            case "Name (Z-A)":
            {
                DefaultTableModel tableModel = (DefaultTableModel) Task_table.getModel();
                for (int i = 0; i < Task_table.getRowCount() - 1; i++)
                {
                    for (int j = i + 1; j < Task_table.getRowCount(); j++) {
                        String gt1 = (String) tableModel.getValueAt(i, 0);
                        String gt2 = (String) tableModel.getValueAt(j, 0);
                        if (gt1.compareTo(gt2) < 0)
                        {
                            Vector<Object> rowData1 = new Vector<>(tableModel.getDataVector().get(i));
                            // Get the data of row 2
                            Vector<Object> rowData2 = new Vector<>(tableModel.getDataVector().get(j));
                            // Set the data of row 1 to row 2
                            tableModel.getDataVector().set(i, rowData2);
                            // Set the data of row 2 to row 1
                            tableModel.getDataVector().set(j, rowData1);
                        }
                    }
                }
                tableModel.fireTableDataChanged();
                break;
            }

            case "Deadline":
            {
                DefaultTableModel tableModel = (DefaultTableModel) Task_table.getModel();
                for (int i = 0; i < Task_table.getRowCount() - 1; i++)
                {
                    for (int j = i + 1; j < Task_table.getRowCount(); j++) {
                        String gt1 = (String) tableModel.getValueAt(i, 3);
                        String gt2 = (String) tableModel.getValueAt(j, 3);
                        if (CheckDeadLine(gt1,gt2) == true)
                        {
                            Vector<Object> rowData1 = new Vector<>(tableModel.getDataVector().get(i));
                            // Get the data of row 2
                            Vector<Object> rowData2 = new Vector<>(tableModel.getDataVector().get(j));
                            // Set the data of row 1 to row 2
                            tableModel.getDataVector().set(i, rowData2);
                            // Set the data of row 2 to row 1
                            tableModel.getDataVector().set(j, rowData1);
                        }

                    }
                }
                tableModel.fireTableDataChanged();
                break;
            }

            case "Priority":{
                DefaultTableModel tableModel = (DefaultTableModel) Task_table.getModel();
                for (int i = 0; i < Task_table.getRowCount() - 1; i++)
                {
                    for (int j = i + 1; j < Task_table.getRowCount(); j++) {
                        String gt1 = (String) tableModel.getValueAt(i, 2);
                        String gt2 = (String) tableModel.getValueAt(j, 2);
                        if (gt1.compareTo(gt2)>0)
                        {
                            Vector<Object> rowData1 = new Vector<>(tableModel.getDataVector().get(i));
                            // Get the data of row 2
                            Vector<Object> rowData2 = new Vector<>(tableModel.getDataVector().get(j));
                            // Set the data of row 1 to row 2
                            tableModel.getDataVector().set(i, rowData2);
                            // Set the data of row 2 to row 1
                            tableModel.getDataVector().set(j, rowData1);
                        }
                    }
                }
                tableModel.fireTableDataChanged();
                break;
            }

        }
    }//GEN-LAST:event_View_labelMouseClicked

    private void Task_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Task_tableMouseClicked
        
        selectedRow = Task_table.getSelectedRow();
        String Taskname = "";
        DefaultTableModel model = (DefaultTableModel)Task_table.getModel();
        boolean value = (boolean)model.getValueAt(selectedRow, 4);
        
        if(value == true )
        {
            Taskdone++;
            TotalTask++;
            Taskname = (String) model.getValueAt(selectedRow, 0);
            model.removeRow(selectedRow);
            JButtonDelete.setEnabled(false);
            String text = "<html>Bạn đã hoàn thành nhiệm vụ " + "<font color='red'>" + Taskname +"</font>"+". Keep up the good work!!!" + "</html>";
            JLabel lb = new JLabel(text);
            Font font = lb.getFont();
            Font newFont = font.deriveFont(20f);
            lb.setFont(newFont);
            Inbox_panel.add(lb);
            Inbox_panel.revalidate();
        } else JButtonDelete.setEnabled(true);
        Taskdone_label.setText(Taskdone + "/" + LimitTask);
        try{
            File inputFile = new File(Username_label.getText() + ".txt");
            BufferedReader reader = new BufferedReader(new FileReader(inputFile));
            StringBuilder content = new StringBuilder();
            String line;
            while ((line = reader.readLine()) != null) {
                String[] p = line.split("|");
                String tn1 = p[0];
                if (!tn1.equals(Taskname)) {
                } else {
                    content.append(line).append(System.lineSeparator());
                } 
            }
            reader.close();
            java.io.FileWriter fw = new java.io.FileWriter(Username_label.getText() + ".txt");
            BufferedWriter writer = new BufferedWriter(fw);
            writer.write(content.toString());
            writer.close();
            
            FileWriter File_pr = new FileWriter(Username_label.getText() + "_pr.txt");
            BufferedWriter w_pr = new BufferedWriter(File_pr);
            w_pr.write(Taskdone + "|" + LimitTask + "|" + TotalTask);
            w_pr.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_Task_tableMouseClicked
  
    private void Menu_iconMenu_Clicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu_iconMenu_Clicked
        if(jPanel3.isVisible() == true){
            jPanel3.setVisible(false);
        }
        else{
            jPanel3.setVisible(true);
        }
    }//GEN-LAST:event_Menu_iconMenu_Clicked

    private void Home_iconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_iconMouseClicked
        Inbox_panel.setVisible(false);
        Tasktable_panel.setVisible(true);
        Papa_AddTask_Panel.setVisible(true);
        AddTask_panel.setVisible(false);
    }//GEN-LAST:event_Home_iconMouseClicked

    private void Search_TextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search_TextFieldFocusGained
        if(Search_TextField.getText().trim().equals("Search")){
            Search_TextField.setText("");
        }
    }//GEN-LAST:event_Search_TextFieldFocusGained

    private void Search_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Search_TextFieldFocusLost
        if(Search_TextField.getText().trim().equals("")){
            Search_TextField.setText("Search");
        }
    }//GEN-LAST:event_Search_TextFieldFocusLost

    private void Search_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Search_TextFieldKeyReleased
        DefaultTableModel tableModel = (DefaultTableModel) Task_table.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(tableModel);
        Task_table.setRowSorter(obj);
        obj.setRowFilter(RowFilter.regexFilter(Search_TextField.getText()));
    }//GEN-LAST:event_Search_TextFieldKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        AddTask_panel.setVisible(false);
        Inbox_panel.setVisible(false);
        DefaultTableModel tableModel = (DefaultTableModel) Task_table.getModel();
         
        try{     
        java.io.FileReader fr = new java.io.FileReader(Username_label.getText() + ".txt");
        java.io.BufferedReader br = new java.io.BufferedReader(fr);

        String line;
        while ((line = br.readLine()) != null){
        String[] p = line.split("\\|");
        String Taskname = p[0];
        String Description = p[1];
        String Priority = p[2];
        String Deadline = p[3];
        String Done = p[4];

        tableModel.addRow(new Object[] {Taskname, Description,Priority, Deadline, Boolean.parseBoolean(Done)});
            }
        tableModel.fireTableDataChanged();
        }
        catch(java.io.IOException e){
            System.out.println("Something was wrong");
            e.printStackTrace();  
        }
    }//GEN-LAST:event_formWindowOpened

    private void Taskdone_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Taskdone_labelMouseClicked
        RewardForm rwf = new RewardForm();
        rwf.setVisible(true);
        rwf.setLocationRelativeTo(null);
    }//GEN-LAST:event_Taskdone_labelMouseClicked

    private void JButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonDeleteActionPerformed

    private void JButtonDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JButtonDeleteMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Task_table.getModel();
        model.removeRow(selectedRow);
        if (model.getRowCount() == 0) JButtonDelete.setEnabled(false);
    }//GEN-LAST:event_JButtonDeleteMouseClicked

    private void Priority_cbbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Priority_cbbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Priority_cbbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTask_panel;
    private javax.swing.JLabel Date;
    private com.toedter.calendar.JDateChooser Date_tf;
    private javax.swing.JTextField Description_tf;
    private javax.swing.JLabel Home_icon;
    private javax.swing.JLabel Inbox_icon;
    private javax.swing.JLabel Inbox_label;
    private javax.swing.JPanel Inbox_panel;
    private javax.swing.JScrollPane Inbox_scrPane;
    private javax.swing.JButton JButtonDelete;
    private javax.swing.JLabel Menu_icon;
    private javax.swing.JPanel Panel_inbox;
    private javax.swing.JPanel Papa_AddTask_Panel;
    private javax.swing.JComboBox<String> Priority_cbb;
    private javax.swing.JTextField Search_TextField;
    private javax.swing.JLabel Search_icon;
    private javax.swing.JLabel SetDate_label;
    private javax.swing.JTable Task_table;
    private javax.swing.JLabel Taskdone_label;
    private javax.swing.JTextField Taskname_tf;
    private javax.swing.JPanel Tasktable_panel;
    private javax.swing.JLabel Time_label;
    private javax.swing.JLabel Today_icon;
    private javax.swing.JLabel Today_label;
    private javax.swing.JPanel Today_panel;
    private javax.swing.JLabel User_icon;
    private javax.swing.JLabel Username_label;
    private javax.swing.JComboBox<String> View_cbb;
    private javax.swing.JLabel View_label;
    private javax.swing.JPanel Welcome_panel;
    private javax.swing.JButton addtask_btn;
    private javax.swing.JLabel addtask_label;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
